"""add_release_type

Revision ID: 4e743ac76aed
Revises: b6d649e9bdb0
Create Date: 2026-02-12 01:37:22.604580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4e743ac76aed'
down_revision: Union[str, Sequence[str], None] = 'b6d649e9bdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_type', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.create_index(batch_op.f('ix_albums_release_type'), ['release_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_release_type'))
        batch_op.drop_column('release_type')

    # ### end Alembic commands ###
