"""add missing indexes: views, featured, upload_date

Revision ID: 91469e4c0110
Revises: 4e743ac76aed
Create Date: 2026-04-12 23:14:04.918167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91469e4c0110'
down_revision: Union[str, Sequence[str], None] = '4e743ac76aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_upload_date'), ['upload_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_views'), ['views'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_views'))
        batch_op.drop_index(batch_op.f('ix_albums_upload_date'))
        batch_op.drop_index(batch_op.f('ix_albums_featured'))

    # ### end Alembic commands ###
