"""add_duration_and_metal_archives_url

Revision ID: b6d649e9bdb0
Revises: 034a7252eb9b
Create Date: 2026-02-12 01:18:26.677707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6d649e9bdb0'
down_revision: Union[str, Sequence[str], None] = '034a7252eb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metal_archives_url', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_albums_youtube_video_id'), ['youtube_video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_youtube_video_id'))
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('metal_archives_url')

    # ### end Alembic commands ###
