GITHUB = "https://github.com/danielbanariba"
LINKEDIN = "https://www.linkedin.com/in/danielbanariba/"
FACEBOOK = "https://www.facebook.com/profile.php?id=100063668491929"
INSTAGRAM = "https://www.instagram.com/danielbanariba/"
YOUTUBE = "https://www.youtube.com/channel/UCa5U18nMgHUsqg-zsE1779Q"
TIKTOK = "https://www.tiktok.com/@danielbanariba"
DANIEL_BANARIBA = "https://www.danielbanariba.com"
EMAIL = "danielbanariba@protonmail.com"