from enum import Enum

class Font(Enum):
    PRESS_START_2P = "Press-Start-2P"
    MONTSERRAT = "Montserrat"
    ROBOTO = "Roboto"
    ROBOTO_MONO = "Roboto Mono"
    ROBOTO_SLAB = "Roboto Slab"
    ROBOTO_CONDENSED = "Roboto Condensed"
    ROBOTO_CONDENSED_ITALIC = "Roboto Condensed Italic"
    ROBOTO_CONDENSED_BOLD = "Roboto Condensed Bold"
    ROBOTO_CONDENSED_BOLD_ITALIC = "Roboto Condensed Bold Italic"
    ROBOTO_MEDIUM = "Roboto Medium"
    ROBOTO_MEDIUM_ITALIC = "Roboto Medium Italic"
    ROBOTO_LIGHT = "Roboto Light"
    ROBOTO_LIGHT_ITALIC = "Roboto Light Italic"
    ROBOTO_THIN = "Roboto Thin"
    ROBOTO_THIN_ITALIC = "Roboto Thin Italic"
    ROBOTO_BLACK = "Roboto Black"
    ROBOTO_BLACK_ITALIC = "Roboto Black Italic"
    ROBOTO_BOLD = "Roboto Bold"
    ROBOTO_BOLD_ITALIC = "Roboto Bold Italic"
    ROBOTO_ITALIC = "Roboto Italic"
    ROBOTO_REGULAR = "Roboto Regular"
    ROBOTO_SLAB_THIN = "Roboto Slab Thin"
    ROBOTO_SLAB_THIN_ITALIC = "Roboto Slab Thin Italic"
    ROBOTO_SLAB_LIGHT = "Roboto Slab Light"
    ROBOTO_SLAB_LIGHT_ITALIC = "Roboto Slab Light Italic"
    ROBOTO_SLAB_REGULAR = "Roboto Slab Regular"
    ROBOTO_SLAB_ITALIC = "Roboto Slab Italic"
    ROBOTO_SLAB_BOLD = "Roboto Slab Bold"
    ROBOTO_SLAB_BOLD_ITALIC = "Roboto Slab Bold Italic"
    ROBOTO_SLAB_BLACK = "Roboto Slab Black"
    ROBOTO_SLAB_BLACK_ITALIC = "Roboto Slab Black Italic"
    ROBOTO_SLAB_EXTRA_BOLD = "Roboto Slab Extra Bold"
    ROBOTO_SLAB_EXTRA_BOLD_ITALIC = "Roboto Slab Extra Bold Italic"
    ROBOTO_SLAB_MEDIUM = "Roboto Slab Medium"